[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Jutul = "2b460a1a-8a2b-45b2-b125-b5c536396eb9"
JutulDarcy = "82210473-ab04-4dce-b31b-11573c4f8e0a"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
